# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47d4754e83f777dd3b6326bbbcc198e723dbc8e86bbf558a1649d23533198bca114d59e0f6b1211fd2a3f81166da7032c012db0029034f1efae012fc3b061329

test:
  secret_key_base: d82b7e5de59a47411378280c4ef05b35d03cc3c57de8634b0b83aef4562ef5f90e4d52c61a295549d47c48765ca7d4134472f95dd691edf1699994b8a627c473

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
